services:
  couchdb-livesync:
    image: ghcr.io/thewolf2068/obsidian-livesync-couchdb:1
    container_name: couchdb-livesync
    user: 1000:1000 # Officially 5984, but 1000:1000 works for standard local user mapping
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: changeme
      OLS_HOSTNAME: https://obsidian.yourdomain.com # Alternatively use http://localhost:5984
      OLS_DATABASE: obsidiannotes
      OLS_PASSPHRASE: changeme
      # Optional: override CouchDB port (default 5984)
      # COUCHDB_PORT: 5984
    volumes:
      - ./data:/opt/couchdb/data
    ports:
      - 5984:5984
    restart: unless-stopped
