services:
  couchdb-livesync:
    image: TheWolf2068/obsidian-livesync-couchdb:1
    container_name: couchdb-livesync
    user: 1000:1000 # Whatever, officially you should use 5984 but idk why 
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: changeme
      OLS_HOSTNAME: https://obsidian.yourdomain.com # Alternatively you can do http://localhost:5984
      OLS_DATABASE: obsidiannotes
      OLS_PASSPHRASE: changeme
      # Optional: override CouchDB port (default 5984)
      # COUCHDB_PORT: 5984
    volumes:
      - ./data:/opt/couchdb/data
    ports:
      - 5984:5984
    restart: unless-stopped
